
- name: Configure ldap
  hosts: master-worker
  become: true
  any_errors_fatal: True
  roles:
    - { role: common, download_repo: true }
    - { role: common, add_ip: true }
    - { role: common, add_ldap: true }
