- name: Configure User and set no ssh password for ambari/root/ldapuser
  hosts: master-worker 
  become: true
  any_errors_fatal: True
  roles:
    - { role: common, add_user: true, user1: ambari }
    - { role: common, add_sudoers: true, user1: ambari, sudoer: true, adgroup: "", adnetbios: "" }
    - { role: common, add_sudoers: true, user1: root, sudoer: false, adgroup: "", adnetbios: "" }
    - { role: common, add_sudoers: true, user1: "{{hadoop_admin}}", sudoer: true, adgroup: "{{hadoop_group}}" }
    - { role: common, add_sshkey: true, user1: ambari }  
    - { role: common, add_sshkey1: true, user1: root, passwd1: '{{passwd2}}', when: cloud=='onprem' } 
    - { role: common, add_sshkey2: true, user1: '{{hadoop_admin}}', passwd1: '{{passwd3}}' }
