---

- name: add hosts
  shell: |     
     echo '{{item.ip}} {{item.fqdn}} {{item.server}}' >> /etc/hosts
  with_items: "{{network_list}}"

- name: add dc manually
  shell: |     
     echo '{{dns_name1}} {{ad_server}}.{{ad_domain|lower}} {{ad_server}}' >> /etc/hosts
  
- name: add repo yum
  shell: |     
     echo "{{hostvars[groups['yum'][0]].ansible_host}} {{hostvars[groups['yum'][0]].inventory_hostname}} {{hostvars[groups['yum'][0]].inventory_hostname.split('.')[0]}}" >> /etc/hosts
  when: env=='sit' and cloud!='onprem'
  