---

- name: kinit admin
  shell: |
      sleep 45
      sudo su - 'TEST014\admin' -c 'for i in hdnode1 hdnode2 hdnode3;do ssh -qxn $i "sudo cp -p /etc/security/keytabs/*.keytab .";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode1 hdnode2 hdnode3;do ssh -qxn $i "sudo chown admin@TEST014.ORG *.keytab";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode1 hdnode2 hdnode3;do ssh -qxn $i "kinit -kt hdfs.headless.keytab hdfs-hadoopdev@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode1; do ssh -qxn $i "kinit -kt yarn-ats.hbase-regionserver.service.keytab yarn-ats-hbase/hdnode1.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode2; do ssh -qxn $i "kinit -kt yarn-ats.hbase-regionserver.service.keytab yarn-ats-hbase/hdnode2.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode3; do ssh -qxn $i "kinit -kt yarn-ats.hbase-regionserver.service.keytab yarn-ats-hbase/hdnode3.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode2; do ssh -qxn $i "kinit -kt yarn-ats.hbase-regionserver.service.keytab yarn-ats-hbase/hdnode2.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode3; do ssh -qxn $i "kinit -kt yarn-ats.hbase-regionserver.service.keytab yarn-ats-hbase/hdnode3.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode1; do ssh -qxn $i "kinit -kt yarn.service.keytab yarn/hdnode1.test014.org@TEST014.ORG";done'
      sudo su - 'TEST014\admin' -c 'for i in hdnode2; do ssh -qxn $i "kinit -kt yarn.service.keytab yarn/hdnode2.test014.org@TEST014.ORG";done'
