gpcheck: 1
gpkey_url: "http://{{hostrepo}}/repo/ambari/RPM-GPG-KEY-Jenkins"
clustername: "hadoop{{env}}" 
deleterepo: true
extract_repo: true
artifacts_dest: "{{postgres_java_rootfolder}}"
create_dest: true 
owner_file: root
group_file: root
mode_file: 0755      
owner_folder: root
group_folder: root
mode_folder: 0755      
artifactslist:
    - { url: '{{download_url}}', name: 'jdk-8u112-linux-x64.tar.gz', folder: '{{postgres_java_folder}}' }  
network_list:
  - { ip: "{{hostvars[groups['master'][0]].ansible_host}}", server: "{{hostvars[groups['master'][0]].inventory_hostname.split('.')[0]}}", fqdn: "{{hostvars[groups['master'][0]].inventory_hostname}}" }
  - { ip: "{{hostvars[groups['worker1'][0]].ansible_host}}", server: "{{hostvars[groups['worker1'][0]].inventory_hostname.split('.')[0]}}", fqdn: "{{hostvars[groups['worker1'][0]].inventory_hostname}}" }
  - { ip: "{{hostvars[groups['worker2'][0]].ansible_host}}", server: "{{hostvars[groups['worker2'][0]].inventory_hostname.split('.')[0]}}", fqdn: "{{hostvars[groups['worker2'][0]].inventory_hostname}}" }
  - { ip: "{{hostvars[groups['sql'][0]].ansible_host}}", server: "{{hostvars[groups['sql'][0]].inventory_hostname.split('.')[0]}}", fqdn: "{{hostvars[groups['sql'][0]].inventory_hostname}}" }             
network_list2:
  - { ip: "{{hostvars[groups['master'][0]].ansible_host}}", server: "{{hostvars[groups['master'][0]].inventory_hostname.split('.')[0]}}"}
  - { ip: "{{hostvars[groups['worker1'][0]].ansible_host}}", server: "{{hostvars[groups['worker1'][0]].inventory_hostname.split('.')[0]}}" }
  - { ip: "{{hostvars[groups['worker2'][0]].ansible_host}}", server: "{{hostvars[groups['worker2'][0]].inventory_hostname.split('.')[0]}}" }
tmp_default: '/usr/lib/tmpfiles.d/tmp.conf'
tmp_file_path: '/etc/tmpfiles.d/'
hadoop1log_path: '/hadoop/1/log/'
user1: ambari
u_mask: "022" 
run_master_server: true # false for testing
run_master_member: true # false for dev
soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384
